/* 
----------------------------------------------------------------------------------------------
-- - Company:     N26 Bank
-- - Name:        SurveyEmailHelperTest
-- - Description: Test class for SurveyEmailHelper
-- - @Author: Felipe Gouvea
-- ------------------------------------------------------------------------------------------
--
-- Date              Name               Version                   
----------------------------------------------------------------------------------------------
--       Felipe Gouvea      1.0         
----------------------------------------------------------------------------------------------
*/

@isTest
private class SurveyEmailHelperTest
{

	@testSetup
	static void setup(){
		//Create test data here
	
	
	}

	@isTest
	static void itShould()
	{
		// Given


		// When
		Test.startTest();
		
		
		Test.stopTest();


		// Then
		System.assert(true);
	}
}