/* 
----------------------------------------------------------------------------------------------
-- - Company:     N26 Bank
-- - Name:        ProductInformationContext
-- - Description: Context class to carry information about related objects
-- - @Author: Felipe Gouvea
-- ------------------------------------------------------------------------------------------
--
-- Date              Name               Version                   
----------------------------------------------------------------------------------------------
-- 05/05/2019       Felipe Gouvea      1.0         
----------------------------------------------------------------------------------------------
*/

public class ProductInformationContext {
	
	public static ContactWrapper contextContact {get; set;}
	public static ProductWrapper contextProduct {get; set;}
	
}